// WHAT IS A SUBSEQUENCE? 
// STRINGA = 'ABCDEFGHIJ'
// A SUBSEQUENCE COULD BE ANY ASSORTMENT IN THE ABOVE STRING THAT FOLLOWS ITS SEQUENCE.
// ANY ONE CHARACTER CAN BE SUBSEQUENCE. IF YOU TAKE A SUBSEQUENCE OF MULTIPLE CHARACTERS THEY MUST SHOW UP 
// IN THE SAME SEQUENCE HENCE THE NAME SUBSEQUENCE. 
// FOR EXAMPLE 'A' AND 'AB' ARE SUBSEQUENCES OF STRINGA BUT 'AC' AND 'AJ' ARE ALSO SUBSEQEUNCES BECAUSE THEYRE IN ORDER.
// 'JGA' WOULD NOT BE A SUBSEQUENCE BECAUSE EVEN THOUGH THE CHARACTERS ARE INCLUDED IN STRINGA THEY ARE NOT IN ORDER.
// GIVEN TWO STRINGS STRINGA AND SUBSTRINGA SUCH THAT 
// STRINGA = 'ABCDEFGHIJ' 
// SUBSTRINGA = 'ECDGI'
// A COMMON SUBSEQUENCE OF STRINGA AND SUBSTRINGA COULD INCLUDE : 
// 'CDGI'
// 'EGI'
// GIVEN TWO STRINGS STRINGA AND SUBSTRINGA SUCH THAT 
// STRINGA = 'ABDACE'
// SUBSTRINGA = 'BABCE'
// A COMMON SUBSEQUENCE OF STINGA AND SUBSTRINGA COULD INCLUDE : 
// 'ABCE'
// 'BACE'
const LCS = (strA, strB)=> {
    if (!strA || !strB)  return 0 
    
}